package main

import (
	"flag"
	"fmt"
	"os"
)

func main() {
	var (
		baselineFile = flag.String("baseline", "", "Baseline JSON file (required)")
		knowledgeDir = flag.String("knowledge", "", "Knowledge base directory (required)")
		version      = flag.String("version", "", "TiDB version to validate (e.g., v7.5.0) (required)")
	)
	flag.Parse()

	if *baselineFile == "" || *knowledgeDir == "" || *version == "" {
		fmt.Fprintf(os.Stderr, "Error: --baseline, --knowledge, and --version are required\n")
		fmt.Fprintf(os.Stderr, "\nUsage: %s --baseline=<baseline-file> --knowledge=<kb-dir> --version=<version>\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "\nExample:\n")
		fmt.Fprintf(os.Stderr, "  %s --baseline=baseline/v7.5.0-baseline.json --knowledge=knowledge --version=v7.5.0\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "\nNote: Baseline files should be generated by kb_generator during knowledge base generation.\n")
		fmt.Fprintf(os.Stderr, "      The kb_generator already collects runtime configuration, so no need to start playground again.\n")
		os.Exit(1)
	}

	compareBaselineWithArgs(*baselineFile, *knowledgeDir, *version)
}
